### ISSUE TITLE
DB structure

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#1]
Define logic for main tables

**Comment by yuliyasychugova** [comment]
https://docs.google.com/spreadsheets/d/1PGdu11grlKdHPhmw9_jraA29oa1ndvozmr3bXTC9ZEI/edit?usp=sharing 
This is a document with our questions, will add them in a real time. Would appreciate it if you could find a possibility to answer asap.

**Comment by buzjuka** [comment]
![GarantME.png](https://images.zenhubusercontent.com/59888023f8b79f8376e22961/8d763f8a-21b7-4d1c-ac95-d4a8ff28de0b)
