### ISSUE TITLE
Bloc 5: We already work with 

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#102]
[Design link](https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/59abfdfa130d047f418b6fae)
All images and symbols can downloaded from Zeplin

**Comment by MariaUvarova** [comment]
Works well on all devices

**Comment by EmileKrm** [comment]
Looks good but the images are blury

I found an svg version of all the logos, I will send it to you on slack.

is it complicated to implement?

**Comment by EmileKrm** [comment]
it looks great thank you!
