### ISSUE TITLE
Bloc 6: Want to contact us

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#103]
[Design link](https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/59abfdfa130d047f418b6fae)
All images and symbols can downloaded from Zeplin

**Comment by EmileKrm** [comment]
Use this as background image for location card

![location](https://user-images.githubusercontent.com/25280550/30003211-45ba51e8-90ba-11e7-9d5d-ee3a365c6a16.png)

**Comment by MariaUvarova** [comment]
looks good on all devices

**Comment by EmileKrm** [comment]
Perfect :)
