### ISSUE TITLE
FAQ choice page

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#112]
*** User Story ***

As a **visitor** I want to choose the appropriate Q&As so that **I understand to value proposition**

*** Acceptance criteria ***

- [x] validate designs

**Comment by EmileKrm** [comment]
![garantme_stationf png](https://user-images.githubusercontent.com/25280550/30432596-6c8d8596-9962-11e7-92be-dafa994122d7.jpeg)

**Comment by EmileKrm** [comment]
[Design link](https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/59ac0149efbd442f9df8a025)

**Comment by MariaUvarova** [comment]
looks fine on all devices

**Comment by EmileKrm** [comment]
Looks good but we would like to keep the image behing Garant|me @ Station F on mobile

**Comment by buzjuka** [comment]
changed
