### ISSUE TITLE
University FAQ

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#113]
*** User Story ***

As a **Customer** I want **more information** so that **I can subscribe**

*** Acceptance criteria ***

- [x] User can click on the question he wants to see the answer (javascript: accordion)
- [x] Must be done in a way that we can add questions easily in the YAML

*** Definition of done ***

- [x] Works on mobile 
- [x] Works on Desktop

**Comment by EmileKrm** [comment]
Content:
You can find the content in the [FAQ tab](https://docs.google.com/spreadsheets/d/1PDtB8BQI68W86X_Gfw-cAGv3soGSW-JIl4yYFGnPyFU/edit?pli=1#gid=870884955)

**Comment by EmileKrm** [comment]
here are the designs

[link](https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/59baa1cf3fabda62b203355c)

**Comment by EmileKrm** [comment]
@buzjuka the designs are now up to date

**Comment by MariaUvarova** [comment]
works on all devices
