### ISSUE TITLE
Landlord FAQ

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#114]
*** User Story ***

As a **Customer** I want **more information** so that **I can subscribe**

*** Acceptance criteria ***

- [ ] User can click on the question he wants to see the answer (javascript: accordion)
- [ ] Must be done in a way that we can add questions easily in the YAML

*** Definition of done ***

- [ ] Works on mobile 
- [ ] Works on Desktop

**Comment by EmileKrm** [comment]
Content:
You can find the content in the [FAQ tab](https://docs.google.com/spreadsheets/d/1PDtB8BQI68W86X_Gfw-cAGv3soGSW-JIl4yYFGnPyFU/edit?pli=1#gid=870884955)

**Comment by EmileKrm** [comment]
Here are the designs

[link](https://zpl.io/adYoDnb)

**Comment by MariaUvarova** [comment]
works on all devices
