### ISSUE TITLE
Renter FAQ

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#115]
*** User Story ***

As a **Customer** I want **more information** so that **I can subscribe**

*** Acceptance criteria ***

- [x] Create new table FAQ with question, answer, faq_type(renter landlord university) and position
- [x] Add CRUD functionalities in admin Area 
- [x] User can click on the question he wants to see the answer (javascript: accordion)
- [x] Must be done in a way that we can add questions easily in the YAML

!! translation is provided by I18n 
https://github.com/globalize/globalize#fallback-locales-to-each-other
!! App doesn't need to load YAML file !!
 
*** Definition of done ***

- [x] Works on mobile 
- [x] Works on Desktop

**Comment by EmileKrm** [comment]
Content:
You can find the content in the [FAQ tab](https://docs.google.com/spreadsheets/d/1PDtB8BQI68W86X_Gfw-cAGv3soGSW-JIl4yYFGnPyFU/edit?pli=1#gid=870884955)

**Comment by EmileKrm** [comment]
Here are the designs

[link](https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/59ac018959b9ce083b14c5a7)

**Comment by MariaUvarova** [comment]
misprint - "Build" http://joxi.ru/l2ZK9ooT8NavbA
http://joxi.ru/J2bxWQQc4wvkDr - the line should be less bright

**Comment by buzjuka** [comment]
misprint - fixed
a color from zeplin http://joxi.ru/VrwnbzDiKkg5lA
http://joxi.ru/12M4Z5nH4187Em

**Comment by MariaUvarova** [comment]
works on all devices

**Comment by EmileKrm** [comment]
Looks great! Thank you for recomending this @buzjuka 

Can you add faq english question to FAQ index? [link](http://joxi.net/L21QD58U6VEZ72)

**Comment by buzjuka** [comment]
changed

**Comment by EmileKrm** [comment]
Great thank you

**Comment by EmileKrm** [comment]
There is a bug: Build housing application button should start on-boarding process
Now when user clicks nothing happens

**Comment by MariaUvarova** [comment]
now it works

**Comment by EmileKrm** [comment]
Perfect
