### ISSUE TITLE
Add error message when user uploads a file with an invalid format

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#122]
*** User Story ***

As a **user** I want to **see a message telling me that my upload failed because I used the wrong format** so that **I try again**

**Comment by EmileKrm** [comment]
Error message english: 

Supported formats are: PDF, JPG, PNG .... (Put list of accepted formats)

Error message french: 

Les formats pris en charge sont: PDF, JPG, PNG .... (Put list of accepted formats)

**Comment by buzjuka** [comment]
messages: {
                maxNumberOfFiles: 'Maximum number of files exceeded',
                acceptFileTypes: 'File type not allowed',
                maxFileSize: 'File is too large',
                minFileSize: 'File is too small'
            }

Please provide errors for all these types

**Comment by buzjuka** [comment]
@EmileKrm

**Comment by EmileKrm** [comment]
You want the errors in french?

**Comment by buzjuka** [comment]
You already provided messages for a maxFileSize error.
If you don't want to change other english messages provide only french

**Comment by EmileKrm** [comment]
We agreed on 50mb for max size right?

messages: {
maxNumberOfFiles: 'Maximum number of files exceeded',
acceptFileTypes: 'File type not allowed. use PDF, JPG, PNG',
maxFileSize: 'File is too large must be below 50mb',
minFileSize: 'File is too small'
}

French

messages: {
maxNumberOfFiles: 'Nombre maximal de fichiers dépassés',
acceptFileTypes: 'Type de fichier non autorisé. utiliser PDF, JPG, PNG',
maxFileSize: 'Le fichier est trop grand. Ne pas depasser 50mb',
minFileSize: 'Le fichier est trop petit'
}

**Comment by buzjuka** [comment]
Current max file size is 10mb

**Comment by EmileKrm** [comment]
messages: {
maxNumberOfFiles: 'Maximum number of files exceeded',
acceptFileTypes: 'File type not allowed. use PDF, JPG, PNG',
maxFileSize: 'File is too large must be below 10mb',
minFileSize: 'File is too small'
}

French

messages: {
maxNumberOfFiles: 'Nombre maximal de fichiers dépassés',
acceptFileTypes: 'Type de fichier non autorisé. utiliser PDF, JPG, PNG',
maxFileSize: 'Le fichier est trop grand. Ne pas depasser 10mb',
minFileSize: 'Le fichier est trop petit'
}
