### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#130]
When user signs up he can't continue process unless he validated his email

Is it possible to allow him to continue on-boarding for a certain period of time? 

Does it take a lot of time to implement? if yes we can leave this feature for later

example: application is cancelled if user didn't verify email within 24 hours.

**Comment by buzjuka** [comment]
@EmileKrm 
Divise has existing feature allow_unconfirmed_access_for

example:
We can set this to 1 day.
After 1 day a user cannot login without email confirmation

**Comment by EmileKrm** [comment]
Yes it sounds good to me :)
