### ISSUE TITLE
Garantme mailout

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#132]
For mailing, we have a postmark account. How do wee proceed to implement it?

Do I have to create a new server?

**Comment by yuliyasychugova** [comment]
We can use your account and it's totally ok. Kirill needs to change his code a little right after moving to production.

**Comment by EmileKrm** [comment]
emails to use:
hello@garantme.fr --> Use this email to send confirmation email to user 

notifications@garantme.fr --> Use this email to send notification message to admin

User t.reynaud8@gmail.com has submitted his application
Check this application here

**Comment by buzjuka** [comment]
http://joxi.ru/L21lXGqU6WvlKm

**Comment by EmileKrm** [comment]
@buzjuka is there an issue with the emails?

**Comment by EmileKrm** [comment]
I registered emile.karam@garantme.fr as an admin. But I didn't receive any notification when user subitted his application

**Comment by EmileKrm** [comment]
@buzjuka both admin emile.karam@garantme.fr and thomas.reynaud@garantme.fr are not receiving notifications from notifications@garantme.fr

And we want default app name to be hello@garantme.fr. So when user signs up he must receive a confirmation request form hello@garantme.fr
