### ISSUE TITLE
Registering apps for social media

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#133]
*** Acceptance criteria ***

- [ ] Facebook
- [ ] LinkedIn
- [ ] Twitter
- [ ] Paypal
- [ ] Gmail

**Comment by EmileKrm** [comment]
We previously did that for linkedin

**Comment by yuliyasychugova** [comment]
Kirill will provide you with a checklist which you need to fill in. After that we will do everything for you.

**Comment by EmileKrm** [comment]
@buzjuka 

The Facebook SDK for JavaScript doesn't have any standalone files that need to be downloaded or installed, instead you simply need to include a short piece of regular JavaScript in your HTML that will asynchronously load the SDK into your pages. The async load means that it does not block loading other elements of your page.
The following snippet of code will give the basic version of the Facebook SDK for JavaScript where the options are set to their most common defaults. Insert the following code snippet directly after the opening `<body>` tag on each page you want to use Facebook Analytics. Replace `{your-app-id}` with the App ID and `{latest-api-version}` with the SDK version:

<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '{your-app-id}',
      cookie     : true,
      xfbml      : true,
      version    : '{latest-api-version}'
    });
    FB.AppEvents.logPageView();   
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>Copy Code

**Comment by buzjuka** [comment]
http://joxi.ru/a2XDKngiy7JLe2

**Comment by MariaUvarova** [comment]
the page is too slow
