### ISSUE TITLE
Heroku account

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#134]
One we have all the code I can create a new heroku ad deploy from the console

**Comment by yuliyasychugova** [comment]
Please create a new account on Heroku. Then we will decide who's going to be in charge of deployment everything.

**Comment by EmileKrm** [comment]
I created a new heroku accout and connected it to github but I'm having trouble pushing the code

When I run push heroku master I get the following message 
http://joxi.net/V2V4z6lH0YPeXr

**Comment by EmileKrm** [comment]
@buzjuka I added you as a collaborator on the new heroku account. Invite was sent to buzjukagm@gmail.com
@rtpr1 I added you as a collaborator on the new heroku account. Invite was sent to oleg.kelin@kodep.ru

**Comment by EmileKrm** [comment]
Postgre database added 10,000,000 lines
Heroku redis added

**Comment by EmileKrm** [comment]
https://garantme-app.herokuapp.com/
