### ISSUE TITLE
Database weight

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#136]
For now we can go with the free plan it has a limit of 10,000 lines.

**Comment by yuliyasychugova** [comment]
Unfortunately, we need to have a paid plan because 10,000 lines won't be enough. Only Cities gem that Kirill used contains 50,000 lines. Of course we can shorten it, we can send you a yaml file so you could do that, but I think it's better to have a paid plan.

**Comment by EmileKrm** [comment]
Bought Hobby plan on Heroku
10,000,000 lines
