### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#137]
Is this a feature provided by heroku?

**Comment by yuliyasychugova** [comment]
Yes, you are right. We need to write a backup schedule because Heroku saves 7 last entities. And sometimes it's not enough.

**Comment by yuliyasychugova** [comment]
Also Heroku has quite a complicated policy for Backups. and we need to get back to it a little bit later.

**Comment by rtpr1** [comment]
DB Backups
implemented the item Jenkins garantme-backup-app-db http://jenkins.garantme.fr/
Plan:
Every day at 01.00 the UTC is stored on the S3(garantme-backup-app-db), the last 30 copies.

**Comment by EmileKrm** [comment]
garantme-backup-app-db: sends a back up every day to S3 servers of last 30 copies
30 copies of what?
Let's have I have a problem and I want to use one of the backups, how do I do?

**Comment by rtpr1** [comment]
30 copies of dump db.
'heroku pg:backups:restore'
