### ISSUE TITLE
App monitoring

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#138]
is this a feature provided by heroku?

**Comment by yuliyasychugova** [comment]
No. When the app on Heroku fails, nobody will know about it. It doesn't make sense to monitor an app from Heroku because if the Heroku falls, your monitoring system falls as well. 

https://www.pingdom.com/free is a good option for you.

**Comment by rtpr1** [comment]
yandex.ru
login:garantme-app@yandex.ru
pass:asder123cvf
The account of the e-mail from which the letters "garantme-monitoring" is sent

http://jenkins.garantme.fr/job/garantme-monitoring/

**Comment by EmileKrm** [comment]
garantme-monitoring

When soething is wrong it will send an email to garantme-app@yandex.ru?

Why not emile.karam@garantme.fr? Or does it send it to both?

**Comment by rtpr1** [comment]
He will mail garantme-app@yandex.ru to notifications@garantme.fr
and emile.karam@garantme.fr
