### ISSUE TITLE
DNS Setup

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#139]
I worked with cloudfare and Gandi

**Comment by yuliyasychugova** [comment]
Did you mean CloudfLare? @EmileKrm

**Comment by EmileKrm** [comment]
yes :) https://www.cloudflare.com/

**Comment by EmileKrm** [comment]
We will use gandi because I can't add a collaborator on cloudfare
Kirill has access:
https://docs.google.com/spreadsheets/d/1onpxxtdQCt9H5mhf9RE9kBVF2IcWYkJJPNYYaleAdxY/edit#gid=0
