### ISSUE TITLE
Terms of service

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#146]
- [x] Add terms of service tab in footer
- [x] Create terns of service page

**Comment by EmileKrm** [comment]
@buzjuka do we have to add the terms of service to the website in order to pass social media reviews?

if yes let's do this task
if not we can do this task later

**Comment by EmileKrm** [comment]
Here are the designs [link](https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/59ad51140552259d1a8d4b52)

Here is the content with the HTML [link](https://docs.google.com/document/d/1Fgd2D9H6xwITHhqRgyJHxvtXmv8JRQKX6PnpAxAY_JE/edit#)

**Comment by MariaUvarova** [comment]
works fine on all devices
