### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#171]
**Home page main CTA**

http://recordit.co/t8FtLeGDNo

When user is on landing page the url is
www.garantme.fr
user clicks on EN url becomes www.garantme.fr/en
user clicks on let's go url becomes www.garantme.fr/en/social_media and it breaks because user doesn't have an account

user should have redirected to www.garantme.fr/en/users/sign_up

**Landlord main CTA**

- [x] Main CTA: When user clicks on learn more he should be redirected to landlord FAQ page

- [ ] Lead generation card: When user clicks on learn more he should be redirected to landlord FAQ page

**Comment by MariaUvarova** [comment]
doesn't work

**Comment by MariaUvarova** [comment]
As far as I understand this button http://joxi.ru/a2Xl9ooCyJbX62 should redirect to landlord FAQ page not just FAQ page. Am I right?

**Comment by EmileKrm** [comment]
As far as I understand this button http://joxi.ru/a2Xl9ooCyJbX62 should redirect to landlord FAQ page not just FAQ page. Am I right?

Sorry my mistake, this one should redirect to renter FAQ

**Comment by MariaUvarova** [comment]
http://joxi.ru/a2Xl9ooCyJbX62 should redirect to https://garant-me.herokuapp.com/en/faqs/renter

**Comment by MariaUvarova** [comment]
the button doesn't work at all
