### ISSUE TITLE
Language Management

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#177]
- [x] Change default language to French

- [x] Replace EN/FR with flags

Here are the designs for the flags
https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/59f48b865538524a666f9661

**Comment by EmileKrm** [comment]
@byzg I have updated the zeplin so that you can export the assets
Only implement the flags in this task (don't create a About us Tab)

**Comment by MariaUvarova** [comment]
don't see any changes, default language is still English, no flags http://joxi.ru/BA0QEllCBdapxr

**Comment by MariaUvarova** [comment]
works fine
