### ISSUE TITLE
Adapt marketing text

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#179]
- [x] Landlord main message EN: Guaranteed renters for free
- [x] Landlord main message FR: Vos loyers garantis gratuitement
- [ ] highlight certified - guaranteed and free
- [x] Value proposition in the following order: Certified - Guaranteed - Free
- [x] put 4 minutes de questionnaire
- [x] Replace how does it work by how to apply
- [x] fix typo in Step 3: landlords ask for
- [x] Landlord Lead generation card: gratuitement pour le proprietaire FR/EN
- [x] Someone has requested a link to change your password. You can do this through the link below. --> Not Someone --> You. Ensuite on dit "If you did not, then ignore..." Donc You.
- [x] Lead gen landlord Vous souhaiter garantir votre loyer gratuitement avec un locataire au profil certifié  ? On vous recontacte
- [x] Like Pierre-Yves said, 3 punchlines to coin every time : Loyers garantis / Locataires certifiés / Offre gratuite pour les bailleurs
- [x] Remove ","
- [x] TOP les drapeaux ! Mets une majuscule à Landlord sur la maquette pour Kirill

**Comment by MariaUvarova** [comment]
highlight certified - guaranteed and free http://joxi.ru/xAeyqYwSYek4jA
fix typo in Step 3: landlords ask for http://joxi.ru/E2p34eDIBePkDm
Someone has requested a link to change your password. You can do this through the link below. --> Not Someone --> You. Ensuite on dit "If you did not, then ignore..." Donc You  - can't see this link

**Comment by EmileKrm** [comment]
fixed typo
Don't know how to do the highlight, we will do it another time, I need to work on the design first :P

**Comment by MariaUvarova** [comment]
I didn't get these items:
Landlord Lead generation card: gratuitement pour le proprietaire FR/EN
Lead gen landlord Vous souhaiter garantir votre loyer gratuitement avec un locataire au profil certifié  ? On vous recontacte
Like Pierre-Yves said, 3 punchlines to coin every time : Loyers garantis / Locataires certifiés / Offre gratuite pour les bailleurs
Remove ","
TOP les drapeaux ! Mets une majuscule à Landlord sur la maquette pour Kirill

**Comment by EmileKrm** [comment]
Sorry these were personal comments, it's some text edits that I made. don't worry about it
