### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#188]
- [ ] Remove email verification

**Comment by MariaUvarova** [comment]
http://joxi.ru/BA0QEllCBdaPxr when tried to sign up

**Comment by MariaUvarova** [comment]
works fine

**Comment by MariaUvarova** [comment]
when you click on save and next http://joxi.ru/ZrJB9ooc1vxapr, it goes like http://joxi.ru/4AkLnRRUMYJQpr

**Comment by byzg** [comment]
@MariaUvarova I cant reproduce this, could you recheck?

**Comment by MariaUvarova** [comment]
Now it works
