### ISSUE TITLE
Pricing DB

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#195]
*** User Story ***

As a **Admin** I want a **Pricing Model** so that I can calculate **the price of every application**

*** Acceptance criteria ***

- [ ] Must create pricing table
- [ ] Must create all variables in [pricing table](https://docs.google.com/spreadsheets/d/1rImZ7zeEPdIZtxymqpwe5qGcThATnoPR-pyzfSD69UA/edit?ts=59f6e38f#gid=1467431108)
- [ ] Must link pricing table to application

*** Definition of done ***

- [ ] Andrei verifies structure
- [ ] All variables have been correctly added

**Comment by MariaUvarova** [comment]
works fine
