### ISSUE TITLE
Pricing settings

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#197]
*** User Story ***

As a **Admin** I want to see **Application pricing section in Application view** so that **I can start calculating pricing**

*** Acceptance criteria ***

- [x] In Admin Application view, create a section called Application pricing
- [x] In this section Admin must see all variables taken into account in the calculation ([See pricing table in formulas tab](https://docs.google.com/spreadsheets/d/1rImZ7zeEPdIZtxymqpwe5qGcThATnoPR-pyzfSD69UA/edit?ts=59f6e38f#gid=2126513283))
NB: don't implement Promo Code variables for now
- [x] Admin can edit the fields in application pricing
- [x] Implement formulas so that pre-filled fields are filled correctly
- [x] Implement fields that needs manual input from admin
NB: you can give these fields a default value of 0
- [x] Implement fields that are calculated automatically
- [x] Implement calculation button that when clicked start calculation for the automatic fields
- [x] create a tick box named pricing calculation validated
- [x] Admin must manually tick this box at the end of every calculation

*** Definition of done ***

- [x] Calculations should be accurate (verify values with excel)
- [x] All fields must be visible and editable in Active admin
- [x] Pricing section should be separated in Application view so that it is clear for Admin
- [x] Editable fields should be separated in Application Edit so that it is clear for admin
- [x] Admin can overwride calculated fields
- [x] Admin can redo calculation with overwritten variables

**Comment by EmileKrm** [comment]
Implement fields that are calculated automatically
> All fields must be visible and editable in Active admin
Should calculated automatically fields be editable? 
**Yes**

> Implement calculation button that when clicked start calculation for the automatic fields
how should calculation be impelented on fronend (using Javasript) or it's enough to calculate on backend with saving of filled data? 
**Yes, let's start with only backend and I will check during stating if it's enough**

> Admin must manually tick this box at the end of every calculation
Am I right that submit button should be blocked until the box ticked?
**Yes, To be clear: it's only one box Not a box per calculated field**

> Admin can redo calculation with overwritten variables
Could you give more information how redo should be?
On the first calculation:
1 - Admin sees **pre-filled** variables.
2 - Admin fills manual variables
3 - Admin clicks on calculate and then sees the results for all **Automatic calculation variables**

Admin wants to Redo calculations with different variables
1 - Admin edits **pre-filled** variables
2 - Clicks on calculate and then sees the new results of  **Automatic calculation variables**

NB: Calculate button takes only Pre-filled and manual variables

is it clearer now?

**Comment by byzg** [comment]
Yes, it's clear. Thanks

**Comment by MariaUvarova** [comment]
http://joxi.ru/DrlKX33T4eMXLA these calculations doesn't seem right

**Comment by EmileKrm** [comment]
@MariaUvarova I can't check this ticket in staging: (Am I on the right staging?)

**Comment by EmileKrm** [comment]
@byzg there is something confusing when admins modify pricing:

When admin modifies pricing and runs calculation

Manual values [link](http://joxi.net/BA0jBQ7cBovEXm) keep the same values as before 
so it's confusing to admin and he can't validate calculation because the numbers don't match.

I've take a video to illustrate the issue [link](http://recordit.co/JzpdfJJ44h)
