### ISSUE TITLE
Application pricing index

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#216]
*** User Story ***

As a Admin I want to see in each row user name and application number so that I can quicly Identify the right application with the proper pricing

*** Acceptance criteria ***

**In Admin Action Change Pricings index**: [link](http://joxi.net/v29a5REUGqRnW2)
- [x] Add user name column with a link to user show [link](http://joxi.net/J2bbOxnT4EgbG2) 
- [x] Add application number with a link to application show [link](http://joxi.net/J2bbOxnT4EgbG2) 
- [x] Allow admin to filter by user name and by application number [link](http://joxi.net/BA0jBQ7cBovaNm)

*** Definition of done ***

- [x] Must be able to filter with user name and application number
- [x] Must be able to click on user name and application number
- [x] Redirections work properly

**Comment by MariaUvarova** [comment]
works fine

**Comment by EmileKrm** [comment]
I can't see the modifications on staging

**Comment by byzg** [comment]
I've just deployed dev to the staging

**Comment by byzg** [comment]
merged to master
