### ISSUE TITLE
Fix language links and flags

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#230]
Fix this urgently we are going on TV Monday night

**Language management seems to be affected every time admin makes modifications to FAQs link**

- [ ] English flag is not displayed [link](http://joxi.net/nAykWpZTXN6JDm)
- [ ] English is not being loaded 
- [ ] Broken links when we switch from language to language

[link](http://recordit.co/iGhPhr2w4a)

- [ ] push live so that it's ready when we are on TV

**Comment by byzg** [comment]
@EmileKrm is it reproduced for you now? I can't reproduce it https://drive.google.com/file/d/14VbVVMSIDT1HcSM_USV1vHRlvXYT9hI4/view

**Comment by EmileKrm** [comment]
@byzg I managed to reproduce it:
1- go to garantme.fr/admin
2 - got to FAqs
3 - Make edits to one question
4- Save it

Or

1- go to garantme.fr/admin
2 - got to FAqs
3 - Click on edit
4- Click on back without saving
