### ISSUE TITLE
Paypal connect

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#24]
*** User Story ***

As a **Customer** I want **to connect my Paypal** so that **I improve my trust score**

*** Acceptance criteria ***

- [x] Must be able to retrieve basic Paypal information

*** Definition of done ***

- [x] Successful test of Paypal connect on localhost and Heroku

**Comment by EmileKrm** [comment]
Issue with paypal connect

![image](https://user-images.githubusercontent.com/25280550/29415412-47c4bb54-8363-11e7-9b28-6bd75c666ffb.png)

**Comment by buzjuka** [comment]
PayPal has resolved problem.
Sanbox app is available
test credentials:
email: test-2@garantme.com
password: garantme
email: test@garantme.com
password: garantme

**Comment by MariaUvarova** [comment]
works fine

**Comment by EmileKrm** [comment]
I can't verify. maybe my paypal email is not in sandbox? emile.karam@hec.edu

**Comment by buzjuka** [comment]
I cannot add real account to sanbox app.
You should use only test credentials above in order to check it.

**Comment by EmileKrm** [comment]
Works well thank you :)
