### ISSUE TITLE
SMTP settings

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#28]
*** Acceptance criteria ***

- [ ] Must be able to register Sign up info user info

**Comment by yuliyasychugova** [comment]
You can now check it, it works.

**Comment by EmileKrm** [comment]
Doesn't work for me
I used emile.karam@hec.edu
Got an error message and didn't receive email
![image](https://user-images.githubusercontent.com/25280550/29272292-ac09944c-80ff-11e7-8bf2-9c7485312622.png)

**Comment by EmileKrm** [comment]
When I try a second time it says that the email has already been taken

![image](https://user-images.githubusercontent.com/25280550/29272347-e67ed902-80ff-11e7-904a-2d50d9f3cf61.png)

**Comment by EmileKrm** [comment]
When I try to login with the credentials the platform tells me that I have to confirm the email but I can't find the email in my inbox.
![image](https://user-images.githubusercontent.com/25280550/29272604-0f91f5b2-8101-11e7-8516-6d9afccea0e2.png)
