### ISSUE TITLE
Step one: Adding layouts from Zeplin for Build Trust view

### ISSUE THREAD

**Issue by yuliyasychugova** [Garantme/Garantme_application#32]
https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/598c7985a1f0c405e0cc92cc 

Here's the Zeplin version

**Comment by EmileKrm** [comment]
@buzjuka if you are having trouble with the trust bar you can use the strength bar in LinkedIn profiles as a basis
![image](https://user-images.githubusercontent.com/25280550/29306066-01e69f26-819c-11e7-9e82-c120bf8e758f.png)

**Comment by MariaUvarova** [comment]
1) That doesn't look appropriate http://joxi.ru/8AnaknniqoXKP2
2) Change the font http://joxi.ru/v29RB88cGR9QjA it should be like this http://joxi.ru/52aX6DDHGgBZ5m
3) The heading should be in the left corner. Make the font of it bigger http://joxi.ru/Grql7kkCNRVypA like this one http://joxi.ru/a2Xl9ooCylMa12 and make it in bold typing
4) Make more space in the right http://joxi.ru/krDgBoou0gWZlA make the font bigger like his one http://joxi.ru/KAg5aLLFgNj7Vm
5) There should be more space between the button and he text http://joxi.ru/xAeyKWWSYb75GA The text should be of gray color like this http://joxi.ru/brRg9oouQLM60m
6) Add "professional" there http://joxi.ru/zANM9ooIl8XVL2
7) Make the squares narrower http://joxi.ru/KAxplqqt4vYRLA like this http://joxi.ru/RmzBGMMcWjQOPm
8) This buttons look different from what it should be http://joxi.ru/52aX6DDHGgBBDm
they should be like this http://joxi.ru/eAOE9ooc46QQ8m
9) Make the button bigger http://joxi.ru/YmEgBoouZBeegA

**Comment by MariaUvarova** [comment]
1) go to https://garant-me.herokuapp.com/social_media_forms/new
2) The design looks appropriate http://joxi.ru/l2ZK9ooT8RWjwA http://joxi.ru/eAOE9ooc46j86m
3) You can also check it on different mobile devices
Result: the design looks appropriate

**Comment by EmileKrm** [comment]
@MariaUvarova The card of linkedin seems bigger than the rest pushing the checkmark outside of the screen. 

@buzjuka if it is easier, we can put a hover with a different color over the card when it is connected. I don't really care about the check mark as long as the user knows which accounts he connected.

![image](https://user-images.githubusercontent.com/25280550/29411777-89488ffe-8356-11e7-82a8-8bcc66fb6fda.png)

**Comment by yuliyasychugova** [comment]
@EmileKrm I'm afraid it won't be easier, let's keep the way it looks now. As for LinkedIN, we will fix it asap.

**Comment by EmileKrm** [comment]
Also the intermediary size between phone  and ipad is not really working. Maybe put each social media card on one line earlier. 

Not very important because iPad format and phone format looks good so if it is not an easy fix we can move to something else

![image](https://user-images.githubusercontent.com/25280550/29412435-19679f92-8359-11e7-8ffa-de928000979f.png)

![image](https://user-images.githubusercontent.com/25280550/29412427-0e2106aa-8359-11e7-8cd0-8af4a9d25cf0.png)

**Comment by yuliyasychugova** [comment]
@EmileKrm
1) https://gyazo.com/3e0a7cc0d23bfa1ed344d9bb2783c4e8 
https://gyazo.com/1b844efab88dfaa6c56fce2f9f41df00
About the checkmark - should it look like this? This way this checkmark is not above the display. As for the size, yes, it appeared to be 6 px more than other buttons, we will fix it as well. 

2) About responsive - intermediary size between phone  and ipad - it's possible to do but will take more time to fix it. If we're about to concentrate on functionalities, it's better to leave for now.

**Comment by EmileKrm** [comment]
Let's leave it for now then

**Comment by yuliyasychugova** [comment]
@EmileKrm Please check Linkedin issue, should work fine now. If it's okay, let's merge changes to master, and we will show you other back end functionalities.

**Comment by EmileKrm** [comment]
@yuliyasychugova everything seems to work fine with the trust bar.
However Paypal is not working
![image](https://user-images.githubusercontent.com/25280550/29415492-8629e072-8363-11e7-9d01-ff19336be46f.png)

**Comment by yuliyasychugova** [comment]
@EmileKrm functionalities shouldn't work, it's a part about layouts only. The next part about functionalities is being developed in another branch.

**Comment by yuliyasychugova** [comment]
@EmileKrm by Linkedin issue I meant the size of a button :)

**Comment by EmileKrm** [comment]
Ah ok everything looks good then
