### ISSUE TITLE
Admin notifications

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#50]
*** User Story ***

As an Admin I want to receive emails when a user signs up and upload new documents so that I can help user complete the on-boarding

*** Acceptance criteria ***

- [ ] Admin receives email with new user info when he signs up
**Email example:** New Garantme user: emile.karam@hec.edu

- [ ] Admin receives email every time user submits application
**Email example:** User emile.karam@hec.edu has submitted his application

*** Definition of done ***

- [ ] Successfully receive emails according to the action users do

**Comment by buzjuka** [comment]
@EmileKrm 
1. '!!! don't send email before the first application submittal !!!' - which acceptance criteria does this refer to?
2. I don't see any mockups for these mails on Zeplin. Are they exist anywhere? =)

**Comment by EmileKrm** [comment]
1- this comment is not relevant anymore, I forgot to delete it
2- The are no mockups, the email to admin is just text. Use the two examples I gave you

**Comment by buzjuka** [comment]
Got it, thanks.

**Comment by buzjuka** [comment]
@EmileKrm Should we notify all admin users or some special ones?

**Comment by EmileKrm** [comment]
We will notify only one email address
support@garantme.fr

**Comment by buzjuka** [comment]
@EmileKrm got it.
About subject - yes, np. Should I apply this subject to all admin notifications or to some special one?

**Comment by EmileKrm** [comment]
Yes, for now we only have those two anyways no?

**Comment by buzjuka** [comment]
Right.

**Comment by buzjuka** [comment]
@EmileKrm Maybe we should add a link to user's profile to mail content? Thus admin'll be able to easily 'come and see' user in the app.

**Comment by EmileKrm** [comment]
Great idea! thanks for thinking about it.

Check his profile here link

**Comment by buzjuka** [comment]
@EmileKrm Got it.

Can we clarify one low-level moment? We send notifications in two exact cases:
1. New user has signed up (notification *New Garantme user...*).
2. A user submits or re-submits (updates already submitted) application (notification *User ... has submitted his application*).

Is it right?

**Comment by EmileKrm** [comment]
Yes.

**Comment by MariaUvarova** [comment]
works well

**Comment by EmileKrm** [comment]
I am not receiving an email when I submit
