### ISSUE TITLE
Admin document management

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#51]
*** User Story ***

As an Admin I want to manage the documents of my users so that I can validate their application

*** Acceptance criteria ***
- [ ] Creating an Application show tab in Admin panel where you see all documents uploaded by user (3.5)
- [ ] Js iframe for preview document implementation (3)
- [ ] Download option for every document (2)

*** Definition of done ***

- [ ] Download must work properly
- [ ] Admin area shows the right documents for each user

**Comment by EmileKrm** [comment]
@buzjuka can we apply the same logic as in task 49? As an admin I edit the fields directly in DB

**Comment by EmileKrm** [comment]
In this video you can see how we used to manage application status (The tick boxes)
[video](http://recordit.co/FrLYGEZOja)

**Comment by EmileKrm** [comment]
@buzjuka you can use the following documents to do your tests:
[test documents](https://drive.google.com/drive/u/1/folders/0B4cm2V76C2RcN1JjTnVJOUx0dzg)

**Comment by yuliyasychugova** [comment]
@EmileKrm what kind of tests would you like Kirill to have?

**Comment by EmileKrm** [comment]
Upload and download, nothing complicated. I just put typical documents there so that he doesn't waste time to look for documents :p
