### ISSUE TITLE
Excel export

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#52]
*** User Story ***

As an Admin I want to export all my user data in an excel sheet so that I can run analysis

*** Acceptance criteria for application excel export ***

We need all the on-boarding information to be extracted in one csv file to do our analysis
We did something similar in our prototype: [excel export video](http://recordit.co/h0Dc7DuYsA)

- [x] Add user profile information in excel export
- [x] Add user responsible party information in excel export
- [x] Add social media user info in excel export
- [x] Add school info in excel export

*** Acceptance criteria for user in admin area ***

- [x] Add a user tab in active admin [link](http://joxi.net/a2Xb5l6TyQ3npr)

Show:
- [x] when clicking on one user I can see user information and all of his applications (application id with a link to the application)

*** Definition of done ***

- [x] Excel contains all necessary fields
- [x] User index and user show have all the fields and filtering options

**Comment by EmileKrm** [comment]
We want to visualize all the info in one place and download the CSV with all the info.
In the prototype we managed to do something similar but it wasn't very clean:
[excel export video](http://recordit.co/h0Dc7DuYsA)

**Comment by EmileKrm** [comment]
https://images.zenhubusercontent.com/59888023f8b79f8376e22961/8d763f8a-21b7-4d1c-ac95-d4a8ff28de0b

**Comment by buzjuka** [comment]
@EmileKrm about screenshot above - I'm I right thinking that these are the field you want to see on user index and show pages under administration panel?

**Comment by EmileKrm** [comment]
No, I just want them in the excel export.
I have clarified what we want to see in the index and show pages in task

**Comment by EmileKrm** [comment]
@buzjuka is this clearer for users?

User index:
- I want a list of users with school name and creation date

User show:
- User info and the list of his applications. when I click on the application I go the application show

application show and index are detailed in #74

**Comment by buzjuka** [comment]
@EmileKrm yes, but #74 contains info for Applications' pages, not about Users' pages.
But your second answer made it clear, thanks.

**Comment by EmileKrm** [comment]
👍

**Comment by buzjuka** [comment]
@EmileKrm since a single user can have several applications, do you want csv exported file to include all the applications for each user?

**Comment by EmileKrm** [comment]
if you are talking about CSV export in User index: 
No: What we need is user info and the list of application ids only.

What is important in User show is that I can see all the application ids of the user and click on one of them to see the details.

**Comment by buzjuka** [comment]
@EmileKrm yes, thanks. I was mixed up a little after you had sent db fragment, but now I got it.

**Comment by buzjuka** [comment]
@EmileKrm you said, that on Users' index 'I want a list of users with school name and user creation date'. What if some user has several submitted applications with different schools? Which one should we display?

**Comment by buzjuka** [comment]
And the same question about 'Add user responsible party information in excel export': different applications - different parties.

**Comment by EmileKrm** [comment]
1 - Display the last school
2 - Display first name and last name of user as well
3 - We don't want to diplay RP in User, only in application

**Comment by EmileKrm** [comment]
User index:
- user email user first name user last name user school

User show:
- user info + user contact info + list of application id (link to application show)

Is it clear?

**Comment by EmileKrm** [comment]
@buzjuka The RP and school are in the application excel export not user excel export

**Comment by EmileKrm** [comment]
@buzjuka user excel export is not important

**Comment by buzjuka** [comment]
@EmileKrm And one more question about this: 'User index... have all the fields and filtering options' - could you specify filters you need? By now I've created email filter and created_at filter, due to the fields you want. Do you need any others?

**Comment by EmileKrm** [comment]
@buzjuka 

User index:

user email user first name user last name user school
filtering options: Admin can filter the index by email, first name of user, last name of user and school

Normally these filters are created automatically by active admin. Am I mistaking to think that?

User show:

user info + user contact info + list of application id (link to application show)

Is it clear?

**Comment by MariaUvarova** [comment]
works fine

**Comment by EmileKrm** [comment]
Social Media is missing LinkedIn and Twitter.
Is this the only info we get from social media? [link](http://joxi.net/Q2Kl8gyU9OznYA)

Only TRUE or FALSE? What does the variable t.jsonb contain? [link](http://joxi.net/gmvnQ1dHxeppGm)

**Comment by buzjuka** [comment]
@EmileKrm apparently, I just forgot about LinkedIn and Twitter - will be done in the first half of a day.
About T/F and jsonb field - this field contains different info we obtain from socials. E.g. we get first and last name for user's social profile, and also we get some extra information - likes amount from Facebook, for instance.
I thought that the one thing required is just to know whether user attached his social account or not, but it seems I was wrong.
So, which info of user's social accounts I should paste into CSV? Will it be enough if it's only social acoount's first and last names, or we need something more, or maybe the whole info we are getting via API?

**Comment by EmileKrm** [comment]
@buzjuka 

Ok, let's keep it simple for applications and just put attached or not.
However let's put the whole API information in user.
To keep it clean we put one section for each social media in User show below the list of applications.

If this is a big task we can create a separate ticket

**Comment by buzjuka** [comment]
@EmileKrm yes, I guess it'll be better to do it in a separate task.
So, for this task the only thing remaining is add LinkedIn and Twitter attached flags to CSV, right?

**Comment by EmileKrm** [comment]
Yes

**Comment by MariaUvarova** [comment]
done
