### ISSUE TITLE
Admin application management

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#53]
*** User Story ***

As an Admin I want to manage the application status of my users so that I can monitor their application progress

*** Acceptance criteria ***

- [x] Must be able to manually modify application_certified_at
- [x] Must be able to manually modify lease_validated_at
- [x] Must be able to manually modify application_guaranteed_at

*** Definition of done ***

- [x] Successful recording of admin modifications

**Comment by EmileKrm** [comment]
@buzjuka this is how we used to manage applications in the prototype. Admin ticks check boxes.
http://recordit.co/FrLYGEZOja

**Comment by MariaUvarova** [comment]
1) go to https://garant-me.herokuapp.com/admin
2) click "Applications" http://joxi.ru/xAeyKWWSYM9VeA
3) choose any User and click "edit" http://joxi.ru/KAxplqqt4VyqMA
4) you see check boxes, tick them http://joxi.ru/Q2Kg9oou9OYXY2 
5) click "Update Application" http://joxi.ru/MAjdOaaUvdWL7m
6) it works http://joxi.ru/VrwyvJJSKo1XD2

**Comment by EmileKrm** [comment]
Everything looks good :)
Great job!
