### ISSUE TITLE
On-boarding success page

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#54]
*** User Story ***

As a **client** I want to see that **I completed the on-boarding process** so that I know **that my application is being taken care of**

*** Acceptance criteria ***

- [x] User is redirected to application edit when clicking on edit CTA

*** Definition of done ***
- [x] Validated design
- [x] Must be able to redirect user to edit

**Comment by EmileKrm** [comment]
Here are the designs:

https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/599aee9da1b9829656c07e86

**Comment by yuliyasychugova** [comment]
1. Go to garant-me.herokuapp.com/users/sign_in
2. Fill in all steps and remember the info you've filled un
3. Go to the success page: layout look all right, button is working.
4. Click on "edit"
5. You get transferred to the last step of onboarding
6.  You can change data here or go to a previous step.
7. After some editing, click to "save and submit" and see the success page again.

**Comment by EmileKrm** [comment]
1 - Missing background picture on on-borading success page [link](http://joxi.net/xAebxykTYM1obr) it should be like this [link](http://joxi.net/DmBy3gacNqOEYr). You should be able to extract the picture from the Zeplin

Edit works well :)

**Comment by EmileKrm** [comment]
@yuliyasychugova the are some bugs that I'm noticing should I put everything in the icebox and we will resolve them in the maintenance phase?
