### ISSUE TITLE
Other school feature

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#56]
*** User Story ***

As a **client** I want to specify **the name of my school if I don't find it** so that **I complete my application**

**Kirill:** When the user doesn't find a school he's in, he sees the following
Instead of "no results found"
he sees "School is not found. Click Here to add it manually"
And then the button appears
Here the user adds information and clicks "Save"

*** Acceptance criteria ***

- [x] Must be able to enter my school name manually

*** Definition of done ***

- [x] Successfully saves new variables
- [x] Admin can validate or disapprove the new school
- [ ] If Admin disapprove school, Admin can select an existing school

**Comment by EmileKrm** [comment]
YY:
Let's imagine the following situation

When you try to find the school you went in but you cannot find it, you have a possibility to type it
and go to the next step.
option 1: Should we add this school to a database without any approval after user typed it?
option 2: we should let them go to the next step but add a possibility to approve or disapprove the school by admins

EK:

if we add it automatically, can Admin edit this information later on?
How much extra time will you need for the approve/disapprove feature?
YY:
We can ask user to input it, add this name of school he entered into db,user goes to the next step and then admin will approve or disapprove this school, so other users would have a possibility to find this school as well.

The only thing we need to work out if what happens if admin disapproves this school
EK:
If admin disapprove school, he can replace it with an existing school?

YY:
I think admin can edit it, yes

**Comment by EmileKrm** [comment]
http://recordit.co/FrLYGEZOja

**Comment by yuliyasychugova** [comment]
1. Step 2 here: https://garant-me.herokuapp.com/responsible_party_forms/new
2. Admin Panel tab here: https://garant-me.herokuapp.com/admin/schools

**Comment by EmileKrm** [comment]
Great job @buzjuka, it works perfectly. I tried all scenarios and I'm really happy with the result :)
