### ISSUE TITLE
Step 3 Layouts

### ISSUE THREAD

**Issue by yuliyasychugova** [Garantme/Garantme_application#60]
Design Implementation

**Comment by MariaUvarova** [comment]
Looks fine http://joxi.ru/eAOE9ooc46yvPm http://joxi.ru/4AkLnRRUM0xjzr

**Comment by MariaUvarova** [comment]
1) go to https://garant-me.herokuapp.com,
2) do the step 1 and click "Save & Next" http://joxi.ru/LmGgBoouRBwj3m,
3) do the step 2 and click "Save & Next" or "Previous" http://joxi.ru/D2Pg9ooudwqbPm 
4) the layout of the step 3 looks fine on different devices http://joxi.ru/12Mg9oou4glPPr http://joxi.ru/823WBXXh6z90q2 http://joxi.ru/4AkLnRRUMjoqzr
5) Result: the page looks well

**Comment by EmileKrm** [comment]
Text should have the same color [link](http://joxi.net/V2V4z6lH08OYbr) use #1b1b1b for all text

**Comment by yuliyasychugova** [comment]
@EmileKrm Look: http://joxi.ru/LmGGVDOhRB7wam
http://joxi.ru/E2pXvg7iBvl7l2
Here are two steps, and the text color is different.

**Comment by EmileKrm** [comment]
Yes my mistake, use this one [link](http://joxi.net/E2pXvg7iBvl7l2)

**Comment by yuliyasychugova** [comment]
Fixed

**Comment by EmileKrm** [comment]
I don;t see the sentence "You need a Responsible Party if you don't have enough income to qualify on your own" anymore [link](http://joxi.net/l2ZbWKdT8RXoE2)

**Comment by EmileKrm** [comment]
This message should appear when clicking No: " We will only take your own revenues into considerations when reviewing your application "

**Comment by yuliyasychugova** [comment]
Done.
