### ISSUE TITLE
Edit application

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#67]
*** User Story ***

As a **client** I want to **edit my application** so that **I can correct or add information**

*** Acceptance criteria ***

- [x] User can see information that was previously entered
- [x] User can see documents that were previously uploaded
- [x] User can edit fields
- [x] User can edit documents

*** Definition of done ***

- [x] Application saves changes correctly

**Comment by EmileKrm** [comment]
User can see documents that were previously uploaded means that when user clicks on edit and goes to my documents, he sees the following:
[User can see which file he has already uploaded](http://joxi.net/DmBy3gacNqgaMr)
instead of only this:
[User can't see which file he has already uploaded](http://joxi.net/VrwX5yLtKojeWm)

**Comment by EmileKrm** [comment]
@yuliyasychugova can we include this task in sprint 3?

**Comment by EmileKrm** [comment]
There seems to be an issue with RP data [video](http://recordit.co/pzHSWsJNHv)
Should we create a debugging ticket for this?

**Comment by buzjuka** [comment]
Sorry. Wrong deploy. I fixed everything.
Please check again.

**Comment by EmileKrm** [comment]
Works perfectly! Great job
