### ISSUE TITLE
Admin can CRUD school

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#69]
*** User Story ***

As an **admin** I want to **create a new school** so that my **DB gets richer**

*** Acceptance criteria ***

- [ ] Admin can create new school
- [x] Admin can read school
- [x] Admin can update school 
- [x] Admin can un-verify school

*** Definition of done ***

- [ ] Successful creation of new school
- [x] Admin can edit an existing school
- [x] When admin un-verifies school it doesn't show in the dropdown menu for other users

**Comment by EmileKrm** [comment]
Admin can't create school
[video](http://recordit.co/IQ0T4fzGGI)

**Comment by EmileKrm** [comment]
What happens if admin delete a school that is being used by a user? is it wise to block the delete fonction and just keep the edit?

**Comment by buzjuka** [comment]
If admin tries to delete school which is tied to application an app returns error
http://joxi.ru/ZrJ4dkRH1kBjj2

**Comment by EmileKrm** [comment]
Perfect!
