### ISSUE TITLE
Admin Application index clean up

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#74]
Index:

- [x] add columns [link](http://joxi.net/Q2Kl8gyU9OQeQA):  
Move in date - Documents uploaded at - Application Submitted at - Application certified at - Apartment contract uploaded at - Apartment contract validated at - Payment processed at

This should be easy because all of the variables belong to application table

![image](https://user-images.githubusercontent.com/25280550/30064353-bc3cce5c-9251-11e7-9be6-a5177b514d0e.png)

- [x] filter by user name or email instead of the object [link](http://joxi.net/DmBy3gacNqlDBr)
- [x] Put filtering options for all variables in application table. Don't do custom school filter. [link](http://joxi.net/V2V4z6lH0BR5Xr). 
- [x] keep ordering arrow at the top of all the columns [link](http://joxi.net/krDJng3C0Gqvd2)

Show: Adding social media

- [x] [Add social media section](http://joxi.net/J2bbOxnT4qJNK2) (like you did for responsible party)
- [x] One section for each social media
- [x] Each section should contain all the information we are getting from the APIs
- [x] Include social media information in the excel export of application

**Comment by EmileKrm** [comment]
@buzjuka we decide to keep social information in Admin. So I updated this task instead of creating a new one

**Comment by MariaUvarova** [comment]
works fine

**Comment by EmileKrm** [comment]
Wow @buzjuka it looks great!

How come we have the liked pages? is it because we are in staging mode? will it still be available when we are live?

**Comment by buzjuka** [comment]
@EmileKrm I think, there'll be no difference, because it's some kinda free information that won't be restricted or underscoped in alive mode. But we should test it when we are live, sure.
