### ISSUE TITLE
Home page front design

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#77]
*** Acceptance criteria ***

- [ ] Implement home page front end design

**Comment by EmileKrm** [comment]
Here are the designs
[link](https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/59abfdfa130d047f418b6fae)

**Comment by EmileKrm** [comment]
Use this for location card

![location](https://user-images.githubusercontent.com/25280550/30003211-45ba51e8-90ba-11e7-9d5d-ee3a365c6a16.png)

**Comment by yuliyasychugova** [comment]
Do we need to make only layout or functionalities as well?

**Comment by EmileKrm** [comment]
This is only for the layout. I've put the functionalities in separate tasks.
