### ISSUE TITLE
User redirection

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#80]
When user logs in:
- [x] If he completed his application, send him to success page
- [x] If he didn't complete his application, send him to the latest completed on-boarding step so that he can resume his application

Apply same logic for my application tab in Navbar drop down menu

**Comment by EmileKrm** [comment]
What happens when a user who is already logged in  click on the home page CTA?
- does he start a new application from scratch?

**Comment by EmileKrm** [comment]
https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/59c4d29631f1bd814339610a

**Comment by MariaUvarova** [comment]
works fine

**Comment by EmileKrm** [comment]
Great job
