### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#81]
- [ ] Update Navbar design: logged in and log out 
- [x] Adapt navbar depending on user status: logged in vs logged out
- [x] Implement dropdown menu with log out and settings features

**Comment by EmileKrm** [comment]
- [ ] Adapt navbar depending on user status: logged in vs logged out
- [ ] Implement dropdown menu with log out and settings features

**Comment by EmileKrm** [comment]
We can use these pre-built components to save time

http://lewagon.github.io/ui-components/#navbar

https://github.com/lewagon/awesome-navbars/blob/master/templates/_navbar_wagon.html.erb

**Comment by EmileKrm** [comment]
Use these pictures for the logo in navbar and footer. That way the typo of the logo won't change on different devices

![garant me_black_logo](https://user-images.githubusercontent.com/25280550/30384526-d5ec1f98-98a4-11e7-9984-b14d4092c038.png)
![garant me_white_logo](https://user-images.githubusercontent.com/25280550/30384527-d5ef682e-98a4-11e7-8b0d-7fac29daf8b3.png)

**Comment by EmileKrm** [comment]
@buzjuka I have the svg version of the logo if needed

I update the dropdown of the navbar with one more tab: my application
https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/59c4d29631f1bd814339610a
The feature of my application is detailed in user redirection task

**Comment by MariaUvarova** [comment]
works fine on all devices

**Comment by EmileKrm** [comment]
Please change Hover color should to brand color #0881A3
http://joxi.net/brRJ0gMCQn3Myr

**Comment by EmileKrm** [comment]
Remove tabs with non existing content
Navabar tabs should be the same on login and logout
http://joxi.net/D2PJMgqCdRal9r

**Comment by buzjuka** [comment]
changed
