### ISSUE TITLE
Profile photo

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#83]
*** User Story ***

As a customer i want to add a picture to my application so that it is more personalised

*** Acceptance criteria ***

- [x] Add user application_photo upload in step 4 my documents (store profile_photo)

*** Definition of done ****

- [x] Implementing new uploader for user - 1.3 hours
- [x] Implementing back-end logics for setting/updating avatar - 2 hours 
- [ ] Implementing front-end input for avatar uploading in account settings page - 2.5 hour

**Comment by EmileKrm** [comment]
[Design link](https://zpl.io/aNNwena)

**Comment by EmileKrm** [comment]
@buzjuka we only need an extra uploader in step 4. Users won't have avatars in the MVP. 
There is no need to add an uploader in settings page.

**Comment by MariaUvarova** [comment]
works fine

**Comment by EmileKrm** [comment]
Works well on both platforms. However user doesn't get an error message when he uploads a document that doesn't have the right format.

can we add the following error message: Wrong format, we only accept jpg, png, pdf

**Comment by buzjuka** [comment]
Earlier we discussed that issue and you said it's okay to leave it like this. Should we add this error message anyway? If yes, please create a different task for that.
