### ISSUE TITLE
add user source field

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#84]
**User story**

Customer informs Garantme where he heard about the service

*** Acceptance criteria ***

- [x] implement question in Step 2
- [x] Add variable user_source in step 2
- [x] Implement dropdown menu: Facebook - Linkedin - Twitter - Google - My school - A landlord - An agency - A friend - My parents - Other
- [ ] Field is mandatory

*** Definition of done ***

- [x] Implementing back-end logics - 2.5 hours
- [x] Modification to 'My profile' form - 0.3 hours
- [x] Modification to CSV - 0.2 hours

Remarks:

**K:** About variable - I think it'll be better to store it in User model, so we won't display this input in any further user's applications if he/she has already noticed this info before.

**Comment by EmileKrm** [comment]
In which model should we put the variable user_source? in the user_model?

**Comment by EmileKrm** [comment]
Here are the designs:
[link](https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/5992a663259ec74eed1857b1)

**Comment by MariaUvarova** [comment]
works on all devices

**Comment by EmileKrm** [comment]
Did you switch branches for staging I can't see the modifications

**Comment by buzjuka** [comment]
```Remarks:

K: About variable - I think it'll be better to store it in User model, so we won't display this input in any further user's applications if he/she has already noticed this info before.
```
After you've submitted profile form first time with filled source field an app don't show it again

**Comment by EmileKrm** [comment]
I see! ok it's good like this then.

However I want the user source field to be available in application csv export. It is available in user csv export but what I meant was application csv so that all the data is in one place

Can you do the necessary modifications?

**Comment by buzjuka** [comment]
Added

**Comment by EmileKrm** [comment]
Great! thank you
