### ISSUE TITLE
Landlord page

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#85]
*** User Story ***

As a **landlord** I want to **check y dedicated page** so **I understand the value proposition**

*** Acceptance criteria ***

- [x] Must be able to click on landlord and land on the appropriate page
- [x] Must be able to submit my email to receive more information

*** Definition of done ***

- [x] Designs are validated
- [x] Email submittal is validated

**Comment by EmileKrm** [comment]
Here are the designs: [link](https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/59ad51140552259d1a8d4b52)

You can get the back ground image from here:

**Comment by EmileKrm** [comment]
@buzjuka you can use this image for landlord page and home page

![5](https://user-images.githubusercontent.com/25280550/30417894-890cb024-9931-11e7-8b51-0028d018e365.png)

**Comment by MariaUvarova** [comment]
works well

**Comment by EmileKrm** [comment]
design looks good but visitors should have access to this page without having to sign in.

It's a public page. Same for FAQ page

**Comment by buzjuka** [comment]
changed
