### ISSUE TITLE
Implement i18n - internationalization

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#87]
*** User Story ***

As a **Customer** I want to **choose between french and english** so that **I understand the content**

*** Acceptance criteria ***

- [x] Implement translation in config locale
- [x] Define routes with en/fr
- [x] Verify that design doesn't break with the translation

*** Definition of done ***

- [x] User can choose the language from the navbar
- [x] Validated designs

!! We will provide you with all the translations !!

**Comment by EmileKrm** [comment]
Works well but there are two minor errors on step 3 of the onboarding

http://joxi.net/Q2Kl8gyU9dGJ0A
http://joxi.net/Rmz1dBaTW5JNyr

**Comment by buzjuka** [comment]
Changed

**Comment by EmileKrm** [comment]
Thank you
