### ISSUE TITLE
Fix social media links

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#90]
open social media links in footer in a new tab. This prevent users from leaving Garantme website

**Comment by EmileKrm** [comment]
Here is the link for our linkedin page

https://www.linkedin.com/company/11191332/

**Comment by buzjuka** [comment]
App has env variable for this GARANTME_IN

**Comment by EmileKrm** [comment]
I don't understand what this means?

**Comment by buzjuka** [comment]
I've set up correct link via env variable.

We will setup a correct link right after we deploy production.
