### ISSUE TITLE
Onboarding form fields

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#93]
Text doesn't fit in tabs

**Comment by EmileKrm** [comment]
Please can you fix the following tabs: 

user can't see the full text http://joxi.net/Dr8ZQalCkPlaJ2
http://joxi.net/V2V4z6lH0YWPXr

There are two options either we make the tabs bigger or we reduce text size.

Which one is simpler?

**Comment by EmileKrm** [comment]
![image](https://user-images.githubusercontent.com/25280550/30800960-ff90c5b0-a1e1-11e7-858c-b402d3b46d3d.png)

**Comment by EmileKrm** [comment]
Reduce the text for all fields to resolve issue everywhere http://joxi.net/p27KDZGI0xgN32
Responsible party fields look very bad on the phone

http://joxi.net/KAge15ySg6b5Jm

make the date fields bigger http://joxi.net/xAebxykTYPxgPr
It looks good on the phone though

**Comment by buzjuka** [comment]
A birthday input field size was increased.
Font size is 16px

**Comment by EmileKrm** [comment]
Fields are not alligned anymore. maybe this happened due to the last changes
http://joxi.net/xAebxykTYP8O7r

**Comment by buzjuka** [comment]
http://joxi.ru/Vm6z94EcxbZwDm
changed

**Comment by EmileKrm** [comment]
RP fields are still not fixed
Reduce text size to solve issue

![IMG_7755.PNG](https://images.zenhubusercontent.com/598838c7f8b79f8376e21fe5/83e12cfa-21f0-47c7-bfe7-ea86186a33c8)

**Comment by buzjuka** [comment]
Which is the browser and device?
http://joxi.ru/EA41X4GCDM3pbr

**Comment by EmileKrm** [comment]
Kirill you are looking at the wrong page. This page is good, I am talking about step 3 Responsible Party. The fields that appear when clicking yes

**Comment by EmileKrm** [comment]
@buzjuka the browser is google chrome and device iphone 6s

**Comment by buzjuka** [comment]
fixed
