### ISSUE TITLE
Bloc 1: Build a certified rental application

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#98]
[Design link](https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/59abfdfa130d047f418b6fae)
All images and symbols can downloaded from Zeplin

**Comment by EmileKrm** [comment]
Use this picture for background

![international flipped](https://user-images.githubusercontent.com/25280550/30268802-31bcea60-96e7-11e7-8333-6ef8afe4d87d.png)

**Comment by yuliyasychugova** [comment]
@EmileKrm  have you got a background page with better quality? It's so blurry :(

**Comment by MariaUvarova** [comment]
On mobile devices and Ipad the picture disappears http://joxi.ru/Dr8aB77iknDEq

**Comment by EmileKrm** [comment]
This is the original picture:

We want to croped it so that there is enough white space on the right for text

![international flipped](https://user-images.githubusercontent.com/25280550/30282021-5536bdb8-9714-11e7-8aab-9e720032bb63.png)

**Comment by EmileKrm** [comment]
@yuliyasychugova keep the picture for now, we will find a better one.

**Comment by EmileKrm** [comment]
http://joxi.net/eAOBgEJt4GW5P2

**Comment by EmileKrm** [comment]
@buzjuka no need for a picture on mobile devices

**Comment by MariaUvarova** [comment]
looks fine

**Comment by EmileKrm** [comment]
Need to fix background color and positioning of baner
[link](http://joxi.net/xAebxykTYVk47r)
