### ISSUE TITLE
Bloc 2: Need a french guarantor?

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#99]
[Design link](https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/59abfdfa130d047f418b6fae)
All images and symbols can downloaded from Zeplin

**Comment by MariaUvarova** [comment]
it works, the layout look fine

**Comment by EmileKrm** [comment]
Looks great

**Comment by buzjuka** [comment]
What is the device?
http://joxi.ru/nAyQbJDFXQk35A

**Comment by buzjuka** [comment]
@EmileKrm

**Comment by MariaUvarova** [comment]
reproduced, will fix tomorrow

**Comment by EmileKrm** [comment]
Iphone 6S

**Comment by MariaUvarova** [comment]
fixed

**Comment by EmileKrm** [comment]
Thank you looks great!
